LANGUAGES = [
    {"lang": 'Arabic_Alarabia-Arabic', "swadesh": None}, 
    {"lang": 'Chinese_Mandarin-GB2312', "swadesh": None}, 
    {"lang": 'Czech_Cesky-UTF8', "swadesh": "cs"}, 
    {"lang": "Danish_Dansk-Latin1", "swadesh": None}, 
    {"lang": 'Dutch_Nederlands-Latin1', "swadesh": "nl"},  
    {"lang": 'English-Latin1', "swadesh": "en"}, 
    {"lang": 'Filipino_Tagalog-Latin1', "swadesh": None}, 
    {"lang": 'Finnish_Suomi-Latin1', "swadesh": None},  
    {"lang": 'French_Francais-Latin1', "swadesh": "fr"}, 
    {"lang": 'German_Deutsch-Latin1', "swadesh": "de"},  
    {"lang": 'Greek_Ellinika-UTF8', "swadesh": None}, 
    {"lang": 'Hebrew_Ivrit-UTF8', "swadesh": None},  
    {"lang": 'Hindi-UTF8', "swadesh": None},  
    {"lang": 'Hungarian_Magyar-Latin1', "swadesh": None},  
    {"lang": 'Icelandic_Yslenska-Latin1', "swadesh": None}, 
    {"lang": 'Italian-Latin1', "swadesh": "it"}, 
    # {"lang": 'Japanese_Nihongo-UTF8', "swadesh": None}, 
    {"lang": 'Korean_Hankuko-UTF8', "swadesh": None}, 
    {"lang": 'Latin_Latina-Latin1', "swadesh": "la"}, 
    {"lang": 'Norwegian-Latin1', "swadesh": None}, 
    {"lang": 'Polish-Latin2', "swadesh": "pl"}, 
    {"lang": 'Portuguese_Portugues-Latin1', "swadesh": "pt"}, 
    {"lang": 'Romanian-Latin2', "swadesh": "ro"}, 
    {"lang": 'Russian-UTF8', "swadesh": "ru"}, 
    {"lang": 'Spanish-Latin1', "swadesh": "es"},  
    {"lang": 'Turkish_Turkce-UTF8', "swadesh": None}, 
    {"lang": 'Ukrainian-UTF8', "swadesh": "uk"},  
    {"lang": 'Vietnamese-UTF8', "swadesh": None}, 
    ]

