LANGUAGES = [
    {"lang": 'Arabic_Alarabia-Arabic'}, 
    {"lang": 'Chinese_Mandarin-GB2312'}, 
    {"lang": 'Czech_Cesky-UTF8'}, 
    {"lang": "Danish_Dansk-Latin1"}, 
    {"lang": 'Dutch_Nederlands-Latin1'},  
    {"lang": 'English-Latin1'}, 
    {"lang": 'Filipino_Tagalog-Latin1'}, 
    {"lang": 'Finnish_Suomi-Latin1'},  
    {"lang": 'French_Francais-Latin1'}, 
    {"lang": 'German_Deutsch-Latin1'},  
    {"lang": 'Greek_Ellinika-UTF8'}, 
    {"lang": 'Hebrew_Ivrit-UTF8'},  
    {"lang": 'Hindi-UTF8'},  
    {"lang": 'Hungarian_Magyar-Latin1'},  
    {"lang": 'Icelandic_Yslenska-Latin1'}, 
    {"lang": 'Italian-Latin1'}, 
    {"lang": 'Japanese_Nihongo-UTF8'}, 
    {"lang": 'Korean_Hankuko-UTF8'}, 
    {"lang": 'Latin_Latina-Latin1'}, 
    {"lang": 'Norwegian-Latin1'}, 
    {"lang": 'Polish-Latin2'}, 
    {"lang": 'Portuguese_Portugues-Latin1'}, 
    {"lang": 'Romanian-Latin2'}, 
    {"lang": 'Russian-UTF8'}, 
    {"lang": 'Spanish-Latin1'},  
    {"lang": 'Turkish_Turkce-UTF8'}, 
    {"lang": 'Ukrainian-UTF8'},  
    {"lang": 'Vietnamese-UTF8'}, 
    ]

